"""add_transcript_status_to_videos

Revision ID: 908b7c486c79
Revises: 39574c39d10d
Create Date: 2026-01-04 01:45:02.759821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908b7c486c79'
down_revision: Union[str, Sequence[str], None] = '39574c39d10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('transcript_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'transcript_status')
    # ### end Alembic commands ###
