"""add_total_videos_to_channels

Revision ID: be3131327d29
Revises: 908b7c486c79
Create Date: 2026-01-04 02:18:17.036066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3131327d29'
down_revision: Union[str, Sequence[str], None] = '908b7c486c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('total_videos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'total_videos')
    # ### end Alembic commands ###
